### ISSUE TITLE
Error: While importing 'manage', an ImportError was raised.

### ISSUE THREAD

**Issue by paul-aussielent** [ksh7/flask-starter#3]
Following your instructions when I get to 'flask initdb' I get the below error.

"Error: While importing 'manage', an ImportError was raised."
"Error: No such command 'initdb'."

**Comment by daniel-mode** [comment]
This is because wtforms has deprecated some classes, check out this page: https://dev.to/sm0ke/cannot-import-name-textfield-from-wtforms-58n8
For example, `TextField` was deprecated in favor of `StringField`.

**Comment by driquelme** [comment]
Checkout this page for an explanation as to why this is happening.
https://dev.to/sm0ke/cannot-import-name-textfield-from-wtforms-58n8

**Comment by berthelemy** [comment]
I fixed this issue by tweaking requirements.txt:

WTForms==2.3.3

This forces pip to install the last 2.x version of WTForms.

If you've already run pip install -r requirements.txt, you'll need to do a 'force-reinstall' to downgrade to the older version of WTForms:

pip install --force-reinstall -r requirements.txt
